CREATE TABLE IF NOT EXISTS posts_b ( 
    post INTEGER NOT NULL UNIQUE AUTOINCREMENT,
    thread INTEGER DEFAULT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email TEXT DEFAULT NULL,
    postName TEXT,
    comment TEXT,
    file TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS posts_know ( 
    post INTEGER NOT NULL UNIQUE AUTOINCREMENT,
    thread INTEGER DEFAULT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email TEXT DEFAULT NULL,
    postName TEXT,
    comment TEXT,
    file TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS boards (
    uri TEXT,
    title TEXT NOT NULL,
    subtitle TEXT,
);
-- 
INSERT INTO boards VALUES
('b', 'Random', NULL)

INSERT INTO boards VALUES
('know', 'Knowledge and Information', NULL)