CREATE TABLE IF NOT EXISTS posts_b ( 
    post INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    thread INTEGER DEFAULT NULL,
    subject TEXT DEFAULT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email TEXT DEFAULT NULL,
    name TEXT,
    comment TEXT,
    file TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS posts_know ( 
    post INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    thread INTEGER DEFAULT NULL,
    subject TEXT DEFAULT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email TEXT DEFAULT NULL,
    name TEXT,
    comment TEXT,
    file TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS boards (
    uri TEXT NOT NULL PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT DEFAULT NULL
);
-- 
-- INSERT INTO boards VALUES
-- ('b', 'Random', NULL);

-- INSERT INTO boards VALUES
-- ('know', 'Knowledge and Information', NULL);